### ISSUE TITLE
errors when using clojure script with idea database

### ISSUE THREAD

**Issue by aristotll** [gregsh/intellij-scripting-plugins#1]
I try to use the plugin with this clojure script https://github.com/aristotll/mine-dg-scripted-extensions-environment/blob/88d2252005364fbf6607558151ba7b991c0370a3/src/main/examples/clojures/generate.clj

modification of original https://github.com/olsh/datagrip-poco-generator/blob/master/deprecated/Generate%20POCO.clj

I have install the scripting closure plugin with the vmoptions enabled: 

stack trace:

```
generate.clj: java.lang.ClassCastException: class clojure.lang.Var$Unbound cannot be cast to class 
com.intellij.database.extensions.Files (clojure.lang.Var$Unbound is in unnamed module of loader 
com.intellij.util.lang.PathClassLoader @224aed64; com.intellij.database.extensions.Files is in unnamed module of loader
 com.intellij.ide.plugins.cl.PluginClassLoader @58d0565a) at examples.clojures.generate$eval352.invokeStatic(Unknown Source) at examples.clojures.generate$eval352.invoke(Unknown Source) at clojure.lang.Compiler.eval(Compiler.java:7177)
 at clojure.lang.Compiler.load(Compiler.java:7636) at clojure.lang.Compiler.load(Compiler.java:7583) at 
clojure.contrib.jsr223.ClojureScriptEngine.eval(ClojureScriptEngine.java:202) at 
clojure.contrib.jsr223.ClojureScriptEngine.eval(ClojureScriptEngine.java:157) at 
java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) in 
IdeScriptEngineManagerImpl$EngineImpl.lambda$eval$1(IdeScriptEngineManagerImpl.java:246)

```

**Comment by aristotll** [comment]
It seems the clojure plugin don't have the correct value injected in the context.

**Comment by aristotll** [comment]
Don't use any namesapces
